version: '3.9'

services:
  api:
    ports:
      # Exposes application port locally for development.
    - "8000:8000"
    volumes:
      # Adds current directory as volume.
    - .:/app/src/
    environment:
      # Enables autoreload.
      KARAOKAY_RELOAD: "True"
      KARAOKAY_LOG_LEVEL: "DEBUG"

  db:
    ports:
      # Exposes db port locally for development.
    - "3306:3306"
